import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import ComponentTemp from './ComponentTemp'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>nextTypescriptSCSS-template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
				<ComponentTemp />
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
